# Generated by Django 4.2.17 on 2024-12-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name displayed on this square.', max_length=255)),
                ('position', models.CharField(help_text='Position of the square (e.g., A1, B2). This determines where it appears on the board.', max_length=2)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ChessBoardSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this sponsor board.', max_length=255, unique=True)),
                ('squares', models.ManyToManyField(blank=True, related_name='boards', to='utils.chesssquare')),
            ],
        ),
    ]
