# Generated by Django 4.2.17 on 2024-12-12 14:16

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_chesssquare_chessboardsnippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chesssquare',
            options={},
        ),
        migrations.RemoveField(
            model_name='chessboardsnippet',
            name='squares',
        ),
        migrations.AddField(
            model_name='chesssquare',
            name='board',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='utils.chessboardsnippet'),
            preserve_default=False,
        ),
    ]
