# Generated by Django 4.2.17 on 2024-12-15 11:47

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_chesssquare_picture_chesssquare_sponsoring_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesssquare',
            name='board',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='utils.chessboardsnippet'),
        ),
    ]
