# Generated by Django 4.2.17 on 2024-12-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_chesssquare_options_and_more'),
        ('standardpages', '0003_alter_indexpage_body_alter_standardpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorboardpage',
            name='board',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='utils.chessboardsnippet'),
        ),
    ]
