# Generated by Django 4.2.17 on 2024-12-18 21:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('standardpages', '0005_calendarpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorboardpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'template': 'components/streamfield/blocks/paragraph_block.html'})}),
        ),
    ]
